---
name: Playwright Tests
'on':
  push:
    branches: [development]
  pull_request:
    branches: [development]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          DEV_URL: ${{ vars.DEV_URL }}
      - name: Read a variable
        run: echo "My Base URL is  value is ${{ vars.DEV_URL }}
      - name: Read a variable second attempt
        run: echo "My Base URL  is ${{ env.DEV_URL }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30