---
name: Playwright Tests
"on":
  push:
    branches: [development]
  pull_request:
    branches: [development]
jobs:
  UI-Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          DEV_URL: ${{ vars.DEV_URL }}
          PLAYWRIGHT_USERNAME: ${{ vars.PLAYWRIGHT_USERNAME }}
          PLAYWRIGHT_PASSWORD: ${{ vars.PLAYWRIGHT_PASSWORD }}
          PLAYWRIGHTALT_USERNAME: ${{ vars.PLAYWRIGHTALT_USERNAME }}
          PLAYWRIGHTALT_PASSWORD: ${{ vars.PLAYWRIGHTALT_PASSWORD }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
