---
name: Playwright Tests
"on":
  push:
    branches: [development]
  pull_request:
    branches: [development]
jobs:
  UI-Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Install Chromium browser
        run: npx playwright install chromium --with-deps
        env:
          DEV_URL: ${{ vars.DEV_URL }}
          PLAYWRIGHT_USERNAME: ${{ vars.PLAYWRIGHT_USERNAME }}
          PLAYWRIGHT_PASSWORD: ${{ vars.PLAYWRIGHT_PASSWORD }}
      - name: Read a variable using vars.
        run: echo "My Base URL is value is ${{ vars.DEV_URL }}"
      - name: Read a variable using env.
        run: echo "My Base URL is ${{ env.DEV_URL }}"
      - name: Run Playwright tests
        run: npx playwright test DEV_URL="${{ env.DEV_URL }}" PLAYWRIGHT_USERNAME="${{ env.PLAYWRIGHT_USERNAME }}" PLAYWRIGHT_PASSWORD="${{ env.PLAYWRIGHT_PASSWORD }}"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
