on:
  pull_request:
  issue_comment:

env:
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
      - name: Read openaikey.
        run: echo " ${{ secrets.OPENAI_KEY }} or ${{env.OPENAI_KEY}}"
      - name: Read github token.
        run: echo " ${{ secrets.GITHUB_TOKEN }} or ${{env.GITHUB_TOKEN}}"
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
